from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("http://practice.automationtesting.in/")
driver.execute_script("window, scrollBy(0, 600);")
item_name = driver.find_element_by_css_selector(".post-160 .woocommerce-LoopProduct-link>h3")
item_name.click()
reviews_tab = driver.find_element_by_css_selector(".reviews_tab>a")
reviews_tab.click()
star_5 = driver.find_element_by_css_selector("a.star-5")
star_5.click()
comment = driver.find_element_by_id("comment")
comment.send_keys("Nice book!")
author = driver.find_element_by_id("author")
author.send_keys("Anna")
email = driver.find_element_by_id("email")
email.send_keys("abcqwerty@ru.ru")
submit = driver.find_element_by_id("submit")
submit.click()
driver.quit()